---
version: "3.8"
services:
   jenkins:
     image: jenkins/jenkins
     ports:
       - 5051:8080
   QAtomcat:
     image: tomee
     ports: 
       - 6061:8080
     links:
       - jenkins 
   PRODtomcat:
     image: tomee
     ports:
       - 7071:8080
     links: 
       - jenkins
...
