---
version: "3.8"
services: 
   apache:
     image: httpd
     ports:
       - 5050:80
   mysql:
     image: mysql
     environment:
       MYSQL_ROOT_PASSWORD: sagar
     links:
       - apache
   php:
     image: php:7.2-apache
     links:
       - apache
       - mysql
...


